"""
VidMuncher Configuration UI Layout.
Colors, window properties, and widget geometry.
"""

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 565
WINDOW_BG_COLOR = "#5B012A"
HEADER_BG_COLOR = "#2D0017"
TEXT_COLOR = "#EFEFEF"
PLACEHOLDER_COLOR = "#725B67"
BUTTON_COLOR = "#89003E"
BUTTON_ACTIVE_COLOR = "#6B0030"
BUTTON_DISABLED_COLOR = "#672845"

class Layout:
    HEADER_HEIGHT = 80
    HEADER_IMAGE_X = 20
    HEADER_IMAGE_Y = 12

    ABOUT_BUTTON_X = 750
    ABOUT_BUTTON_Y = 25
    ABOUT_BUTTON_WIDTH = 30
    ABOUT_BUTTON_HEIGHT = 30

    HISTORY_BUTTON_X = 670
    HISTORY_BUTTON_Y = 25
    HISTORY_BUTTON_WIDTH = 30
    HISTORY_BUTTON_HEIGHT = 30

    SETTINGS_BUTTON_X = 710
    SETTINGS_BUTTON_Y = 25
    SETTINGS_BUTTON_WIDTH = 30
    SETTINGS_BUTTON_HEIGHT = 30

    URL_ENTRY_X = 20
    URL_ENTRY_Y = 100
    URL_ENTRY_WIDTH = 620
    URL_ENTRY_HEIGHT = 35

    VIDEO_INFO_X = 20
    VIDEO_INFO_Y = 150
    VIDEO_INFO_WIDTH = 509
    VIDEO_INFO_HEIGHT = 130

    THUMBNAIL_X = 549
    THUMBNAIL_Y = 150
    THUMBNAIL_WIDTH = 231
    THUMBNAIL_HEIGHT = 130

    PRESET_LABEL_X = 20
    PRESET_LABEL_Y = 300
    PRESET_COMBO_X = 150
    PRESET_COMBO_Y = 300
    PRESET_COMBO_WIDTH = 250
    PRESET_COMBO_HEIGHT = 30

    REENCODE_LABEL_X = 475
    REENCODE_LABEL_Y = 300
    REENCODE_COMBO_X = 530
    REENCODE_COMBO_Y = 300
    REENCODE_COMBO_WIDTH = 250
    REENCODE_COMBO_HEIGHT = 30

    SECTION_CB_X = 150
    SECTION_CB_Y = 340
    SECTION_START_X = 300
    SECTION_START_Y = 340
    SECTION_END_X = 425
    SECTION_END_Y = 340

    SAVE_LABEL_X = 20
    SAVE_LABEL_Y = 380
    SAVE_ENTRY_X = 150
    SAVE_ENTRY_Y = 380
    SAVE_ENTRY_WIDTH = 490
    SAVE_ENTRY_HEIGHT = 30

    ANALYZE_BUTTON_X = 660
    ANALYZE_BUTTON_Y = 100
    ANALYZE_BUTTON_WIDTH = 120
    ANALYZE_BUTTON_HEIGHT = 35

    BROWSE_BUTTON_X = 660
    BROWSE_BUTTON_Y = 380
    BROWSE_BUTTON_WIDTH = 120
    BROWSE_BUTTON_HEIGHT = 30

    DOWNLOAD_BUTTON_X = 340
    DOWNLOAD_BUTTON_Y = 440
    DOWNLOAD_BUTTON_WIDTH = 120
    DOWNLOAD_BUTTON_HEIGHT = 35

    CANCEL_BUTTON_X = 340
    CANCEL_BUTTON_Y = 440
    CANCEL_BUTTON_WIDTH = 120
    CANCEL_BUTTON_HEIGHT = 35

    PROGRESS_X = 20
    PROGRESS_Y = 500
    PROGRESS_WIDTH = 760
    PROGRESS_HEIGHT = 25

    COPYRIGHT_X = 400
    COPYRIGHT_Y = 545

class Fonts:
    DEFAULT = ("Poppins", 10)
    SMALL = ("Poppins", 9)
    BOLD = ("Poppins", 10, "bold")
    COMBO = ("Poppins", 9)
