name: PR Pull
run-name: PR ${{ github.event.number }} 🚀
on:
  pull_request:
    branches:
      - dev
      - main
permissions:
  contents: read
jobs:
  check-format:
    name: Check Formatting 🔍
    uses: ./.github/workflows/check-format.yaml

  build-project:
    name: Build Project 🧱
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
